on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - gh-pages

# see example here https://github.com/marketplace/actions/on-demand-self-hosted-aws-ec2-runner-for-github-actions#example
# We'll need to put a github access token and AWS creds into secrets on g-research org -- is this OK?
# Ensure there's no way for that secret to leak out via forks

# Document go 1.16 limitations
# unsupported for security fixes once 1.19 is released

jobs:
  go-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.16', '1.18' ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/go-setup

      - name: make tests
        run: make tests

      - name: make junit-report
        run: make junit-report

      - name: Upload junit report
        uses: actions/upload-artifact@v2.2.4
        with:
          name: junit.xml
          path: test_reports/junit.xml
